package com.back.simpleDb;

import java.sql.*;
import java.time.LocalDateTime;
import java.util.*;

public class Sql {
    private final SimpleDb simpleDb;
    private final StringBuilder sqlBuilder = new StringBuilder();
    private final List<Object> params = new ArrayList<>();

    public Sql(SimpleDb simpleDb) {
        this.simpleDb = simpleDb;
    }

    public Sql append(String sql, Object... params) {
        if (!sqlBuilder.isEmpty()) sqlBuilder.append(" ");
        sqlBuilder.append(sql);
        this.params.addAll(Arrays.asList(params));
        return this;
    }

    public long insert() {
        try (PreparedStatement pstmt = buildStatement(Statement.RETURN_GENERATED_KEYS)) {
            pstmt.executeUpdate();
            try (ResultSet rs = pstmt.getGeneratedKeys()) {
                if (rs.next()) return rs.getLong(1);
                throw new RuntimeException("삽입 실패");
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public int update() {
        try (PreparedStatement pstmt = buildStatement()) {
            return pstmt.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public int delete() {
        try (PreparedStatement pstmt = buildStatement()) {
            return pstmt.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    // ── stub (미구현) ─────────────────────────────
    public List<Map<String, Object>> selectRows()    { throw new UnsupportedOperationException(); }
    public Map<String, Object> selectRow()           { throw new UnsupportedOperationException(); }
    public LocalDateTime selectDatetime()            { throw new UnsupportedOperationException(); }
    public Long selectLong()                         { throw new UnsupportedOperationException(); }
    public String selectString()                     { throw new UnsupportedOperationException(); }
    public Boolean selectBoolean()                   { throw new UnsupportedOperationException(); }
    public List<Long> selectLongs()                  { throw new UnsupportedOperationException(); }
    public Sql appendIn(String sql, Object... params){ throw new UnsupportedOperationException(); }
    public <T> List<T> selectRows(Class<T> clazz)   { throw new UnsupportedOperationException(); }
    public <T> T selectRow(Class<T> clazz)           { throw new UnsupportedOperationException(); }
    // ─────────────────────────────────────────────

    void execute() {
        try (PreparedStatement pstmt = buildStatement()) {
            pstmt.execute();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    private PreparedStatement buildStatement() throws SQLException {
        return buildStatement(Statement.NO_GENERATED_KEYS);
    }

    private PreparedStatement buildStatement(int autoGeneratedKeys) throws SQLException {
        String sql = sqlBuilder.toString();
        if (simpleDb.isDevMode()) {
            System.out.println("== rawSql ==\n" + sql);
        }
        PreparedStatement pstmt = simpleDb.getConnection().prepareStatement(sql, autoGeneratedKeys);
        for (int i = 0; i < params.size(); i++) {
            pstmt.setObject(i + 1, params.get(i));
        }
        return pstmt;
    }
}